import type { Template } from '@prescriptionmaker/types'

// =============================================================================
// PREMIUM TEMPLATE CATALOG — 12 Distinct Professional Templates
// Designed after real medical letterheads used by top specialists worldwide
// =============================================================================

export const TEMPLATES: Omit<Template, 'id' | 'usageCount' | 'createdAt' | 'updatedAt'>[] = [

  // 1. Royal Indigo — Inspired by user reference images (purple Rx style)
  {
    name: 'Royal Indigo',
    slug: 'royal-indigo',
    description: 'Iconic Rx symbol, structured patient grid with DOB/Age/Sex/Allergies, and professional drug table. Used by top hospital consultants.',
    category: 'clinic',
    layout: 'royal-indigo',
    preview: '/templates/previews/royal-indigo.png',
    thumbnail: '/templates/thumbnails/royal-indigo.png',
    styles: {
      primaryColor: '#4338ca',
      secondaryColor: '#6366f1',
      accentColor: '#818cf8',
      bgColor: '#f5f5ff',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'logo-left',
      medicineTableStyle: 'grid',
      signatureStyle: 'bottom-right',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'header', name: 'Clinic Header with Rx', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Information Grid', visible: true, order: 2 },
      { id: 'medicines', name: 'Drug Table', visible: true, order: 3 },
      { id: 'advice', name: 'Advice', visible: true, order: 4 },
      { id: 'signature', name: "Doctor's Signature", visible: true, order: 5 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 20, right: 20, bottom: 20, left: 20 }, showWatermark: false },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['premium', 'indigo', 'rx', 'hospital', 'grid'],
    seoTitle: 'Royal Indigo Premium Prescription Template',
    seoDescription: 'Premium purple Rx-style prescription template with patient grid and professional drug table.',
  },

  // 2. Executive Gold
  {
    name: 'Executive Gold',
    slug: 'executive-gold',
    description: 'Luxury gold accent borders. Centered clinic header, full patient block with health insurance fields, detailed medicine table. Trusted by senior consultants.',
    category: 'specialty',
    layout: 'executive-gold',
    preview: '/templates/previews/executive-gold.png',
    thumbnail: '/templates/thumbnails/executive-gold.png',
    styles: {
      primaryColor: '#1a1a2e',
      secondaryColor: '#16213e',
      accentColor: '#c9a84c',
      bgColor: '#fffef7',
      fontFamily: 'Georgia, serif',
      headerStyle: 'centered',
      medicineTableStyle: 'bordered',
      signatureStyle: 'bottom-right',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'header', name: 'Centered Clinic Header', visible: true, order: 1 },
      { id: 'patient', name: 'Full Patient Block', visible: true, order: 2 },
      { id: 'vitals', name: 'Vitals (BP/Pulse/Weight)', visible: true, order: 3 },
      { id: 'diagnosis', name: 'Diagnosed With', visible: true, order: 4 },
      { id: 'medicines', name: 'Prescription Table', visible: true, order: 5 },
      { id: 'advice', name: 'Diet & Brief History', visible: true, order: 6 },
      { id: 'signature', name: "Doctor's Signature & Stamp", visible: true, order: 7 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 22, right: 22, bottom: 22, left: 22 } },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['premium', 'gold', 'luxury', 'consultant', 'senior'],
    seoTitle: 'Executive Gold Premium Prescription Template',
    seoDescription: 'Luxury gold accent prescription for senior consultants with full patient details.',
  },

  // 3. Emerald Specialist
  {
    name: 'Emerald Specialist',
    slug: 'emerald-specialist',
    description: 'Deep emerald for cardiology, surgery, and internal medicine. Two-column header, numbered medicine rows with detailed dosage fields.',
    category: 'specialty',
    layout: 'emerald-specialist',
    preview: '/templates/previews/emerald-specialist.png',
    thumbnail: '/templates/thumbnails/emerald-specialist.png',
    styles: {
      primaryColor: '#064e3b',
      secondaryColor: '#065f46',
      accentColor: '#10b981',
      bgColor: '#f0fdf4',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'two-col-divided',
      medicineTableStyle: 'numbered-rows',
      signatureStyle: 'bottom-right',
      footerStyle: 'colored-band',
    },
    sections: [
      { id: 'header', name: 'Specialist Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Details', visible: true, order: 2 },
      { id: 'vitals', name: 'Vitals', visible: true, order: 3 },
      { id: 'diagnosis', name: 'Clinical Diagnosis', visible: true, order: 4 },
      { id: 'medicines', name: 'Medicines (Numbered)', visible: true, order: 5 },
      { id: 'tests', name: 'Lab Investigations', visible: true, order: 6 },
      { id: 'advice', name: 'Advice', visible: true, order: 7 },
      { id: 'followup', name: 'Follow-up Date', visible: true, order: 8 },
      { id: 'signature', name: 'Signature & Registration', visible: true, order: 9 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 18, right: 20, bottom: 18, left: 20 } },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['specialist', 'emerald', 'cardiology', 'surgery', 'internal-medicine'],
    seoTitle: 'Emerald Specialist Prescription Template',
    seoDescription: 'Premium emerald prescription for cardiology and surgery specialists.',
  },

  // 4. Sapphire Hospital
  {
    name: 'Sapphire Hospital',
    slug: 'sapphire-hospital',
    description: 'Institutional hospital prescription with full OPD header, department label, MRN/IP number fields, comprehensive patient grid, and dual signature block.',
    category: 'hospital',
    layout: 'sapphire-hospital',
    preview: '/templates/previews/sapphire-hospital.png',
    thumbnail: '/templates/thumbnails/sapphire-hospital.png',
    styles: {
      primaryColor: '#1e3a8a',
      secondaryColor: '#1d4ed8',
      accentColor: '#93c5fd',
      bgColor: '#eff6ff',
      fontFamily: 'Arial, sans-serif',
      headerStyle: 'hospital-banner',
      medicineTableStyle: 'hospital-grid',
      signatureStyle: 'dual',
      footerStyle: 'institutional',
    },
    sections: [
      { id: 'hospital-header', name: 'Hospital Banner Header', visible: true, order: 1 },
      { id: 'department', name: 'Department & OPD/IPD', visible: true, order: 2 },
      { id: 'patient', name: 'Patient Grid (MRN/DOB/Insurance)', visible: true, order: 3 },
      { id: 'vitals', name: 'Vitals Block', visible: true, order: 4 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 5 },
      { id: 'medicines', name: 'Prescribed Medicines', visible: true, order: 6 },
      { id: 'tests', name: 'Investigations', visible: true, order: 7 },
      { id: 'advice', name: 'Discharge Advice', visible: true, order: 8 },
      { id: 'signature', name: 'Doctor & HOD Signatures', visible: true, order: 9 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 10, right: 15, bottom: 15, left: 15 } },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['hospital', 'sapphire', 'opd', 'ipd', 'institutional', 'mrn'],
    seoTitle: 'Sapphire Hospital Prescription Template',
    seoDescription: 'Institutional hospital OPD prescription with department, MRN, and dual signature block.',
  },

  // 5. Platinum Minimal
  {
    name: 'Platinum Minimal',
    slug: 'platinum-minimal',
    description: 'Ultra-premium white space design for elite private practices. Hairline borders, platinum accent, Playfair typography. Favored by AIIMS-level consultants.',
    category: 'clinic',
    layout: 'platinum-minimal',
    preview: '/templates/previews/platinum-minimal.png',
    thumbnail: '/templates/thumbnails/platinum-minimal.png',
    styles: {
      primaryColor: '#111827',
      secondaryColor: '#374151',
      accentColor: '#9ca3af',
      bgColor: '#ffffff',
      fontFamily: 'Georgia, serif',
      headerStyle: 'elegant-centered',
      medicineTableStyle: 'hairline',
      signatureStyle: 'bottom-right',
      footerStyle: 'hairline',
    },
    sections: [
      { id: 'header', name: 'Elegant Centered Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient', visible: true, order: 2 },
      { id: 'diagnosis', name: 'Clinical Notes', visible: true, order: 3 },
      { id: 'medicines', name: 'Rx', visible: true, order: 4 },
      { id: 'tests', name: 'Investigations', visible: true, order: 5 },
      { id: 'advice', name: 'Instructions', visible: true, order: 6 },
      { id: 'signature', name: 'Signature', visible: true, order: 7 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 35, right: 28, bottom: 35, left: 28 } },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['platinum', 'minimal', 'luxury', 'elite', 'private-practice'],
    seoTitle: 'Platinum Minimal Premium Prescription Template',
    seoDescription: 'Ultra-premium minimal prescription for elite private practices with hairline borders.',
  },

  // 6. Crimson Cardiology
  {
    name: 'Crimson Cardiology',
    slug: 'crimson-cardiology',
    description: 'Bold high-contrast for cardiologists. Dedicated vitals section (BP, HR, SpO2, Weight), cardiac-specific medicine categorization.',
    category: 'specialty',
    layout: 'crimson-cardiology',
    preview: '/templates/previews/crimson-cardiology.png',
    thumbnail: '/templates/thumbnails/crimson-cardiology.png',
    styles: {
      primaryColor: '#7f1d1d',
      secondaryColor: '#991b1b',
      accentColor: '#f87171',
      bgColor: '#fff5f5',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'banner-left',
      medicineTableStyle: 'category-rows',
      signatureStyle: 'bottom-right',
      footerStyle: 'colored-band',
    },
    sections: [
      { id: 'header', name: 'Cardiology Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient & Cardiac Risk Info', visible: true, order: 2 },
      { id: 'vitals', name: 'Vitals (BP/HR/SpO2/Weight)', visible: true, order: 3 },
      { id: 'diagnosis', name: 'Cardiac Diagnosis', visible: true, order: 4 },
      { id: 'medicines', name: 'Medicines', visible: true, order: 5 },
      { id: 'tests', name: 'Cardiac Investigations', visible: true, order: 6 },
      { id: 'advice', name: 'Lifestyle Advice', visible: true, order: 7 },
      { id: 'followup', name: 'Next Review', visible: true, order: 8 },
      { id: 'signature', name: 'Signature', visible: true, order: 9 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 15, right: 18, bottom: 15, left: 18 } },
    isPublished: true, isFeatured: false, isPremium: true,
    tags: ['cardiology', 'cardiac', 'crimson', 'heart', 'specialist'],
    seoTitle: 'Crimson Cardiology Prescription Template',
    seoDescription: 'Professional cardiology prescription with dedicated vitals and cardiac-specific layout.',
  },

  // 7. Teal Modern Clinic
  {
    name: 'Teal Modern Clinic',
    slug: 'teal-modern-clinic',
    description: 'Contemporary teal for urban multi-specialty clinics. Clean sidebar header, color-coded sections, card-style medicine entries.',
    category: 'clinic',
    layout: 'teal-modern',
    preview: '/templates/previews/teal-modern-clinic.png',
    thumbnail: '/templates/thumbnails/teal-modern-clinic.png',
    styles: {
      primaryColor: '#0d9488',
      secondaryColor: '#0f766e',
      accentColor: '#5eead4',
      bgColor: '#f0fdfb',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'sidebar-left',
      medicineTableStyle: 'card',
      signatureStyle: 'inline-right',
      footerStyle: 'teal-band',
    },
    sections: [
      { id: 'header', name: 'Clinic Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Details', visible: true, order: 2 },
      { id: 'vitals', name: 'Vitals', visible: true, order: 3 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 4 },
      { id: 'medicines', name: 'Prescription', visible: true, order: 5 },
      { id: 'tests', name: 'Investigations', visible: true, order: 6 },
      { id: 'advice', name: 'Advice', visible: true, order: 7 },
      { id: 'followup', name: 'Follow-up', visible: true, order: 8 },
      { id: 'signature', name: 'Doctor Signature', visible: true, order: 9 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 15, right: 18, bottom: 15, left: 18 } },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['teal', 'modern', 'urban', 'clinic', 'multi-specialty'],
    seoTitle: 'Teal Modern Clinic Prescription Template',
    seoDescription: 'Contemporary teal prescription for urban multi-specialty clinics.',
  },

  // 8. Ocean Pediatric
  {
    name: 'Ocean Pediatric',
    slug: 'ocean-pediatric',
    description: 'Professional ocean blue for pediatricians. Child-specific fields, weight-based dosing, immunization status, growth parameters.',
    category: 'pediatric',
    layout: 'ocean-pediatric',
    preview: '/templates/previews/ocean-pediatric.png',
    thumbnail: '/templates/thumbnails/ocean-pediatric.png',
    styles: {
      primaryColor: '#0c4a6e',
      secondaryColor: '#0369a1',
      accentColor: '#38bdf8',
      bgColor: '#f0f9ff',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'pediatric-banner',
      medicineTableStyle: 'weight-dosed',
      signatureStyle: 'bottom-right',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'header', name: 'Pediatrician Header', visible: true, order: 1 },
      { id: 'patient', name: 'Child Details', visible: true, order: 2 },
      { id: 'growth', name: 'Growth (Wt/Ht/HC)', visible: true, order: 3 },
      { id: 'vitals', name: 'Vitals', visible: true, order: 4 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 5 },
      { id: 'medicines', name: 'Medicines (Weight-Based)', visible: true, order: 6 },
      { id: 'vaccines', name: 'Immunization Due', visible: false, order: 7 },
      { id: 'tests', name: 'Investigations', visible: true, order: 8 },
      { id: 'diet', name: 'Diet & Nutrition Advice', visible: true, order: 9 },
      { id: 'followup', name: 'Next Visit', visible: true, order: 10 },
      { id: 'signature', name: 'Signature', visible: true, order: 11 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 18, right: 18, bottom: 18, left: 18 } },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['pediatric', 'ocean', 'children', 'immunization', 'weight-dosing'],
    seoTitle: 'Ocean Pediatric Premium Prescription Template',
    seoDescription: 'Professional pediatric prescription with growth parameters and weight-based dosing.',
  },

  // 9. Obsidian Surgeon
  {
    name: 'Obsidian Surgeon',
    slug: 'obsidian-surgeon',
    description: 'High-authority dark-header for surgical consultants. Pre/post-op sections, surgical instructions, two-column layout.',
    category: 'specialty',
    layout: 'obsidian-surgeon',
    preview: '/templates/previews/obsidian-surgeon.png',
    thumbnail: '/templates/thumbnails/obsidian-surgeon.png',
    styles: {
      primaryColor: '#0f172a',
      secondaryColor: '#1e293b',
      accentColor: '#e2e8f0',
      bgColor: '#ffffff',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'dark-banner',
      medicineTableStyle: 'structured-rows',
      signatureStyle: 'bottom-right',
      footerStyle: 'dark-band',
    },
    sections: [
      { id: 'header', name: 'Dark Authority Header', visible: true, order: 1 },
      { id: 'referral', name: 'Referred By', visible: true, order: 2 },
      { id: 'patient', name: 'Patient Details', visible: true, order: 3 },
      { id: 'vitals', name: 'Pre-Op Vitals', visible: true, order: 4 },
      { id: 'history', name: 'Surgical History', visible: true, order: 5 },
      { id: 'diagnosis', name: 'Diagnosis / Procedure', visible: true, order: 6 },
      { id: 'medicines', name: 'Post-Op Medications', visible: true, order: 7 },
      { id: 'tests', name: 'Pre-Op Investigations', visible: true, order: 8 },
      { id: 'advice', name: 'Surgical Instructions', visible: true, order: 9 },
      { id: 'followup', name: 'Review Date', visible: true, order: 10 },
      { id: 'signature', name: 'Consultant Surgeon Signature', visible: true, order: 11 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 0, right: 15, bottom: 15, left: 15 } },
    isPublished: true, isFeatured: false, isPremium: true,
    tags: ['surgeon', 'obsidian', 'dark', 'surgical', 'consultant'],
    seoTitle: 'Obsidian Surgeon Premium Prescription Template',
    seoDescription: 'Dark authority prescription for surgical consultants with pre/post-op sections.',
  },

  // 10. Violet Dermatology
  {
    name: 'Violet Dermatology',
    slug: 'violet-dermatology',
    description: 'Sophisticated violet for dermatologists. Topical vs. systemic medication split, skin examination fields.',
    category: 'specialty',
    layout: 'violet-dermatology',
    preview: '/templates/previews/violet-dermatology.png',
    thumbnail: '/templates/thumbnails/violet-dermatology.png',
    styles: {
      primaryColor: '#4c1d95',
      secondaryColor: '#6d28d9',
      accentColor: '#c4b5fd',
      bgColor: '#faf5ff',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'logo-left',
      medicineTableStyle: 'split-topical-systemic',
      signatureStyle: 'bottom-right',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'header', name: 'Dermatologist Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Details', visible: true, order: 2 },
      { id: 'history', name: 'Chief Complaint & History', visible: true, order: 3 },
      { id: 'findings', name: 'Dermatological Findings', visible: true, order: 4 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 5 },
      { id: 'medicines', name: 'Medications', visible: true, order: 6 },
      { id: 'tests', name: 'Investigations / Biopsy', visible: true, order: 7 },
      { id: 'advice', name: 'Skincare Advice', visible: true, order: 8 },
      { id: 'followup', name: 'Next Appointment', visible: true, order: 9 },
      { id: 'signature', name: 'Signature', visible: true, order: 10 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 18, right: 20, bottom: 18, left: 20 } },
    isPublished: true, isFeatured: false, isPremium: true,
    tags: ['dermatology', 'skin', 'violet', 'topical', 'specialty'],
    seoTitle: 'Violet Dermatology Prescription Template',
    seoDescription: 'Specialized dermatology prescription with topical/systemic medication split.',
  },

  // 11. Slate Corporate
  {
    name: 'Slate Corporate',
    slug: 'slate-corporate',
    description: 'Corporate-grade prescription for occupational health and corporate clinics. Employee fields, fitness-for-duty assessment.',
    category: 'clinic',
    layout: 'slate-corporate',
    preview: '/templates/previews/slate-corporate.png',
    thumbnail: '/templates/thumbnails/slate-corporate.png',
    styles: {
      primaryColor: '#334155',
      secondaryColor: '#475569',
      accentColor: '#0ea5e9',
      bgColor: '#f8fafc',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'corporate-split',
      medicineTableStyle: 'clean-rows',
      signatureStyle: 'bottom-right',
      footerStyle: 'corporate-band',
    },
    sections: [
      { id: 'header', name: 'Corporate Header', visible: true, order: 1 },
      { id: 'patient', name: 'Employee/Patient Details', visible: true, order: 2 },
      { id: 'vitals', name: 'Vitals', visible: true, order: 3 },
      { id: 'diagnosis', name: 'Clinical Assessment', visible: true, order: 4 },
      { id: 'medicines', name: 'Medications', visible: true, order: 5 },
      { id: 'tests', name: 'Tests Ordered', visible: true, order: 6 },
      { id: 'advice', name: 'Work Restrictions / Advice', visible: true, order: 7 },
      { id: 'signature', name: 'Physician Signature', visible: true, order: 8 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 20, right: 22, bottom: 20, left: 22 } },
    isPublished: true, isFeatured: false, isPremium: true,
    tags: ['corporate', 'slate', 'occupational', 'employee', 'fitness'],
    seoTitle: 'Slate Corporate Prescription Template',
    seoDescription: 'Professional corporate medical prescription for occupational health programs.',
  },

  // 12. Rose Gynecology
  {
    name: 'Rose Gynecology',
    slug: 'rose-gynecology',
    description: "Elegant rose for gynecologists. Obstetric history, menstrual cycle notes, trimester fields, hormone therapy tracking.",
    category: 'specialty',
    layout: 'rose-gynecology',
    preview: '/templates/previews/rose-gynecology.png',
    thumbnail: '/templates/thumbnails/rose-gynecology.png',
    styles: {
      primaryColor: '#9d174d',
      secondaryColor: '#be185d',
      accentColor: '#f9a8d4',
      bgColor: '#fff1f2',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'logo-left',
      medicineTableStyle: 'detailed-rows',
      signatureStyle: 'bottom-right',
      footerStyle: 'rose-band',
    },
    sections: [
      { id: 'header', name: "Gynecologist's Header", visible: true, order: 1 },
      { id: 'patient', name: 'Patient Details & OB History', visible: true, order: 2 },
      { id: 'vitals', name: 'Vitals', visible: true, order: 3 },
      { id: 'history', name: 'Menstrual / Obstetric History', visible: true, order: 4 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 5 },
      { id: 'medicines', name: 'Medications', visible: true, order: 6 },
      { id: 'tests', name: 'Investigations (USG/Lab)', visible: true, order: 7 },
      { id: 'advice', name: 'Dietary & Lifestyle Advice', visible: true, order: 8 },
      { id: 'followup', name: 'Next Appointment', visible: true, order: 9 },
      { id: 'signature', name: 'Signature', visible: true, order: 10 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 18, right: 20, bottom: 18, left: 20 } },
    isPublished: true, isFeatured: false, isPremium: true,
    tags: ['gynecology', 'obstetrics', 'rose', 'womens-health', 'pregnancy'],
    seoTitle: 'Rose Gynecology Prescription Template',
    seoDescription: 'Premium gynecology prescription with obstetric history and pregnancy trimester tracking.',
  },
]

export const TEMPLATE_CATEGORIES = [
  { id: 'all', name: 'All Templates', slug: 'all' },
  { id: 'clinic', name: 'Clinic', slug: 'clinic' },
  { id: 'hospital', name: 'Hospital', slug: 'hospital' },
  { id: 'specialty', name: 'Specialty', slug: 'specialty' },
  { id: 'pediatric', name: 'Pediatric', slug: 'pediatric' },
] as const
