import type { Template } from '@prescriptionmaker/types'

// =============================================================================
// PREMIUM TEMPLATE CATALOG — 10 Structurally Distinct Professional Templates
// Each template has a COMPLETELY different layout, sections, and design.
// Not just color variations — genuinely different prescription formats.
// =============================================================================

export const TEMPLATES: Omit<Template, 'id' | 'usageCount' | 'createdAt' | 'updatedAt'>[] = [

  // 1. Classic Letterhead — Centered, elegant, like a printed clinic letterhead
  {
    name: 'Classic Letterhead',
    slug: 'classic-letterhead',
    description: 'Elegant centered letterhead with clinic name as masthead. Simple numbered drug list (no table). Used by senior private practitioners. Looks exactly like a printed letterhead.',
    category: 'clinic',
    layout: 'classic',
    preview: '/templates/previews/classic-letterhead.jpg',
    thumbnail: '/templates/thumbnails/classic-letterhead.jpg',
    styles: {
      primaryColor: '#1a365d',
      accentColor: '#2b6cb0',
      fontFamily: 'Georgia, serif',
      headerStyle: 'centered',
      medicineTableStyle: 'minimal',
      signatureStyle: 'bottom-right',
      footerStyle: 'hairline',
    },
    sections: [
      { id: 'header', name: 'Centered Clinic Letterhead', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Name & Date', visible: true, order: 2 },
      { id: 'complaint', name: 'Chief Complaint', visible: true, order: 3 },
      { id: 'medicines', name: 'Numbered Rx List (no table)', visible: true, order: 4 },
      { id: 'advice', name: 'Advice as bullet points', visible: true, order: 5 },
      { id: 'signature', name: 'Signature centered', visible: true, order: 6 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 25, right: 25, bottom: 25, left: 25 }, showWatermark: false },
    isPublished: true, isFeatured: true, isPremium: false,
    tags: ['letterhead', 'classic', 'serif', 'elegant', 'senior-doctor'],
    seoTitle: 'Classic Letterhead Prescription Template',
    seoDescription: 'Elegant centered clinic letterhead with numbered Rx list.',
  },

  // 2. Two-Column Sidebar — Doctor info on left, Rx on right
  {
    name: 'Two-Column Sidebar',
    slug: 'two-column-sidebar',
    description: 'Split layout: narrow left sidebar with doctor photo, vitals recorded, clinic details — wide right panel with patient info, Rx, and investigations. Used by cardiologists and senior physicians.',
    category: 'specialty',
    layout: 'two-column',
    preview: '/templates/previews/two-column-sidebar.jpg',
    thumbnail: '/templates/thumbnails/two-column-sidebar.jpg',
    styles: {
      primaryColor: '#1e3a5f',
      accentColor: '#3182ce',
      bgColor: '#f7fafc',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'sidebar-left',
      medicineTableStyle: 'striped',
      signatureStyle: 'bottom-right',
      footerStyle: 'minimal',
    },
    sections: [
      { id: 'left-panel', name: 'Doctor Sidebar (Photo, Vitals, Clinic)', visible: true, order: 1 },
      { id: 'right-panel', name: 'Patient + Rx Content', visible: true, order: 2 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 0, right: 0, bottom: 0, left: 0 } },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['two-column', 'sidebar', 'vitals', 'cardiologist', 'physician'],
    seoTitle: 'Two-Column Sidebar Prescription Template',
    seoDescription: 'Split layout with doctor sidebar and Rx panel for cardiologists.',
  },

  // 3. Hospital OPD Form — Institutional hospital format
  {
    name: 'Hospital OPD Form',
    slug: 'hospital-opd',
    description: 'Full institutional hospital format with Patient MRN, Ward, Bed Number, Insurance, Attending Physician, HOD Signature. Used by government and private hospital doctors.',
    category: 'hospital',
    layout: 'modern',
    preview: '/templates/previews/hospital-opd.jpg',
    thumbnail: '/templates/thumbnails/hospital-opd.jpg',
    styles: {
      primaryColor: '#155e75',
      accentColor: '#0ea5e9',
      bgColor: '#f0f9ff',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'hospital-banner',
      medicineTableStyle: 'hospital-grid',
      signatureStyle: 'dual',
      footerStyle: 'institutional',
    },
    sections: [
      { id: 'header', name: 'Hospital Banner', visible: true, order: 1 },
      { id: 'registration', name: 'MRN / Ward / Bed / Date', visible: true, order: 2 },
      { id: 'patient', name: 'Patient Full Details', visible: true, order: 3 },
      { id: 'diagnosis', name: 'Diagnosis / ICD Code', visible: true, order: 4 },
      { id: 'medicines', name: 'Hospital Medicine Table', visible: true, order: 5 },
      { id: 'investigations', name: 'Investigations Ordered', visible: true, order: 6 },
      { id: 'dual-signature', name: 'HOD + Doctor Signatures', visible: true, order: 7 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 0, right: 10, bottom: 10, left: 10 } },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['hospital', 'opd', 'mrn', 'hod', 'institutional'],
    seoTitle: 'Hospital OPD Prescription Form Template',
    seoDescription: 'Institutional hospital OPD format with MRN, ward, HOD and doctor signatures.',
  },

  // 4. SOAP Clinical Notes — Western/academic clinical documentation
  {
    name: 'SOAP Clinical Notes',
    slug: 'soap-clinical',
    description: 'Structured clinical documentation format: Subjective (chief complaint), Objective (vitals + exam), Assessment (diagnosis + ICD), Plan (Rx + investigations + advice). Used by western-trained, academic, and research doctors.',
    category: 'specialty',
    layout: 'specialty',
    preview: '/templates/previews/soap-clinical.jpg',
    thumbnail: '/templates/thumbnails/soap-clinical.jpg',
    styles: {
      primaryColor: '#312e81',
      accentColor: '#6366f1',
      bgColor: '#fafafa',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'banner-left',
      medicineTableStyle: 'structured-rows',
      signatureStyle: 'bottom-right',
      footerStyle: 'minimal',
    },
    sections: [
      { id: 'S', name: 'S — Subjective (Chief Complaint)', visible: true, order: 1 },
      { id: 'O', name: 'O — Objective (Vitals + Exam)', visible: true, order: 2 },
      { id: 'A', name: 'A — Assessment (Diagnosis)', visible: true, order: 3 },
      { id: 'P', name: 'P — Plan (Rx + Investigations + Advice)', visible: true, order: 4 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 0, right: 12, bottom: 12, left: 12 } },
    isPublished: true, isFeatured: false, isPremium: true,
    tags: ['soap', 'clinical-notes', 'academic', 'structured', 'western'],
    seoTitle: 'SOAP Clinical Notes Prescription Template',
    seoDescription: 'Structured SOAP format clinical notes for academic and western-trained doctors.',
  },

  // 5. Vitals-First — For ICU, cardiology, critical care
  {
    name: 'Vitals-First',
    slug: 'vitals-first',
    description: 'Prominently displays vitals grid (BP, HR, Temp, SpO2, RR, Weight) BEFORE the prescription. Critical for cardiologists, intensivists, and physicians. Separate colored boxes for each vital sign.',
    category: 'specialty',
    layout: 'modern',
    preview: '/templates/previews/vitals-first.jpg',
    thumbnail: '/templates/thumbnails/vitals-first.jpg',
    styles: {
      primaryColor: '#9b2335',
      accentColor: '#e53e3e',
      bgColor: '#fff5f5',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'two-col-divided',
      medicineTableStyle: 'bordered',
      signatureStyle: 'bottom-right',
      footerStyle: 'colored-band',
    },
    sections: [
      { id: 'header', name: 'Doctor Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Info', visible: true, order: 2 },
      { id: 'vitals', name: 'Vitals Grid (BP, HR, Temp, SpO2, Weight, RR)', visible: true, order: 3 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 4 },
      { id: 'medicines', name: 'Prescription Table', visible: true, order: 5 },
      { id: 'investigations', name: 'Investigations', visible: true, order: 6 },
      { id: 'advice', name: 'Lifestyle Advice', visible: true, order: 7 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 0, right: 12, bottom: 12, left: 12 } },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['vitals', 'cardiology', 'icu', 'bp', 'critical-care'],
    seoTitle: 'Vitals-First Prescription Template for Cardiologists',
    seoDescription: 'Prescription template with prominent vitals grid for cardiologists and intensivists.',
  },

  // 6. Detailed Drug Card — Each medicine gets its own detail block
  {
    name: 'Detailed Drug Chart',
    slug: 'detailed-drug-chart',
    description: 'Each medicine gets its own structured card with Name, Strength, Form, Route, Dosage, Frequency, Timing (with food/empty stomach), and Special Instructions. Used by specialists who prescribe complex multi-drug regimens.',
    category: 'specialty',
    layout: 'specialty',
    preview: '/templates/previews/detailed-drug-chart.jpg',
    thumbnail: '/templates/thumbnails/detailed-drug-chart.jpg',
    styles: {
      primaryColor: '#065f46',
      accentColor: '#10b981',
      bgColor: '#f0fdf4',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'two-col-divided',
      medicineTableStyle: 'detailed-rows',
      signatureStyle: 'bottom-right',
      footerStyle: 'teal-band',
    },
    sections: [
      { id: 'header', name: 'Doctor Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Info', visible: true, order: 2 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 3 },
      { id: 'medicine-cards', name: 'Detailed Drug Cards (1 per medicine)', visible: true, order: 4 },
      { id: 'investigations', name: 'Investigations', visible: true, order: 5 },
      { id: 'advice', name: 'Advice', visible: true, order: 6 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 0, right: 12, bottom: 12, left: 12 } },
    isPublished: true, isFeatured: false, isPremium: true,
    tags: ['drug-chart', 'detailed', 'complex', 'specialist', 'route', 'timing'],
    seoTitle: 'Detailed Drug Chart Prescription Template',
    seoDescription: 'Each medicine in its own card with dosage, route, timing for specialist doctors.',
  },

  // 7. Multi-Section Boxed — Multiple clearly bordered sections
  {
    name: 'Multi-Section Boxed',
    slug: 'multi-section-boxed',
    description: 'Multiple clearly bordered boxed sections: Chief Complaint, Examination, Diagnosis, Investigations, Prescription, Advice. Each section in its own box. Perfect for pediatricians and surgeons who document systematically.',
    category: 'pediatric',
    layout: 'modern',
    preview: '/templates/previews/multi-section-boxed.jpg',
    thumbnail: '/templates/thumbnails/multi-section-boxed.jpg',
    styles: {
      primaryColor: '#0c4a6e',
      accentColor: '#38bdf8',
      bgColor: '#f0f9ff',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'pediatric-banner',
      medicineTableStyle: 'grid',
      signatureStyle: 'bottom-right',
      footerStyle: 'minimal',
    },
    sections: [
      { id: 'header', name: 'Doctor Header', visible: true, order: 1 },
      { id: 'box-patient', name: 'Patient Info Box', visible: true, order: 2 },
      { id: 'box-complaint', name: 'Chief Complaint Box', visible: true, order: 3 },
      { id: 'box-diagnosis', name: 'Diagnosis Box', visible: true, order: 4 },
      { id: 'box-rx', name: 'Prescription Box', visible: true, order: 5 },
      { id: 'box-investigations', name: 'Investigations Box', visible: true, order: 6 },
      { id: 'box-advice', name: 'Advice Box', visible: true, order: 7 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 0, right: 10, bottom: 10, left: 10 } },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['boxed', 'multi-section', 'pediatric', 'systematic', 'surgical'],
    seoTitle: 'Multi-Section Boxed Prescription Template',
    seoDescription: 'Systematically organized boxed sections for pediatricians and surgeons.',
  },

  // 8. Minimal Print Ruled — Elegant, like premium printed notepad
  {
    name: 'Minimal Print Ruled',
    slug: 'minimal-print-ruled',
    description: 'Ultra-minimal design like a premium printed notepad. Hairline ruled lines under each element, large italic Rx symbol, generous whitespace. No colored headers. Used by elite private clinics in metro cities.',
    category: 'clinic',
    layout: 'minimal',
    preview: '/templates/previews/minimal-print-ruled.jpg',
    thumbnail: '/templates/thumbnails/minimal-print-ruled.jpg',
    styles: {
      primaryColor: '#1a202c',
      accentColor: '#718096',
      bgColor: '#ffffff',
      fontFamily: 'Georgia, serif',
      headerStyle: 'minimal',
      medicineTableStyle: 'hairline',
      signatureStyle: 'inline',
      footerStyle: 'hairline',
    },
    sections: [
      { id: 'header', name: 'Left-aligned clinic name', visible: true, order: 1 },
      { id: 'patient', name: 'Patient, Age, Date on one line', visible: true, order: 2 },
      { id: 'rx-symbol', name: 'Large italic Rx symbol', visible: true, order: 3 },
      { id: 'ruled-meds', name: 'Dotted ruled medicine lines', visible: true, order: 4 },
      { id: 'advice', name: 'Advice', visible: true, order: 5 },
      { id: 'signature', name: 'Signature line', visible: true, order: 6 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 30, right: 30, bottom: 30, left: 30 } },
    isPublished: true, isFeatured: true, isPremium: false,
    tags: ['minimal', 'elegant', 'ruled', 'notepad', 'elite', 'private-clinic'],
    seoTitle: 'Minimal Print Ruled Prescription Template',
    seoDescription: 'Ultra-elegant minimal ruled notepad style prescription for elite private clinics.',
  },

  // 9. Bilingual Indian Format — English + Hindi labels
  {
    name: 'Bilingual Indian',
    slug: 'bilingual-indian',
    description: 'Uniquely Indian prescription with English and Hindi labels side-by-side (मरीज का नाम / Patient Name). Includes patient allergies, Indian address format, and traditional Rx. Popular with general practitioners in Tier 2-3 cities.',
    category: 'general',
    layout: 'traditional',
    preview: '/templates/previews/bilingual-indian.jpg',
    thumbnail: '/templates/thumbnails/bilingual-indian.jpg',
    styles: {
      primaryColor: '#7c3aed',
      accentColor: '#a78bfa',
      bgColor: '#faf5ff',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'centered',
      medicineTableStyle: 'numbered-rows',
      signatureStyle: 'bottom-right',
      footerStyle: 'colored-band',
    },
    sections: [
      { id: 'header', name: 'Bilingual Doctor Header (EN + HI)', visible: true, order: 1 },
      { id: 'patient', name: 'Bilingual Patient Info', visible: true, order: 2 },
      { id: 'diagnosis', name: 'Diagnosis (Bilingual)', visible: true, order: 3 },
      { id: 'medicines', name: 'Numbered Prescription', visible: true, order: 4 },
      { id: 'advice', name: 'Advice (Bilingual)', visible: true, order: 5 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 0, right: 15, bottom: 15, left: 15 } },
    isPublished: true, isFeatured: false, isPremium: false,
    tags: ['bilingual', 'hindi', 'indian', 'gp', 'tier2', 'regional'],
    seoTitle: 'Bilingual Indian Prescription Template (English + Hindi)',
    seoDescription: 'Bilingual English-Hindi prescription template for Indian general practitioners.',
  },

  // 10. Compartmentalized Grid — Modern structured grid layout
  {
    name: 'Compartmentalized Grid',
    slug: 'compartmentalized-grid',
    description: 'Modern grid-based layout with a 3-column top bar (Patient | Age/Sex | Date), full-width diagnosis and complaint bands, structured medicine table, and 2-column footer (Advice | Follow-up). Used by multi-specialty consultants.',
    category: 'specialty',
    layout: 'compact',
    preview: '/templates/previews/compartmentalized-grid.jpg',
    thumbnail: '/templates/thumbnails/compartmentalized-grid.jpg',
    styles: {
      primaryColor: '#92400e',
      accentColor: '#f59e0b',
      bgColor: '#fffbeb',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'corporate-split',
      medicineTableStyle: 'grid',
      signatureStyle: 'bottom-right',
      footerStyle: 'corporate-band',
    },
    sections: [
      { id: 'header', name: 'Doctor Header', visible: true, order: 1 },
      { id: '3col-bar', name: '3-column Patient Bar', visible: true, order: 2 },
      { id: 'complaint-band', name: 'Chief Complaint Band', visible: true, order: 3 },
      { id: 'diagnosis-band', name: 'Diagnosis Band', visible: true, order: 4 },
      { id: 'rx-table', name: 'Grid Rx Table', visible: true, order: 5 },
      { id: '2col-footer', name: '2-column: Advice | Follow-Up', visible: true, order: 6 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 0, right: 0, bottom: 0, left: 0 } },
    isPublished: true, isFeatured: false, isPremium: true,
    tags: ['grid', 'compartmentalized', 'modern', 'multi-specialty', 'structured'],
    seoTitle: 'Compartmentalized Grid Prescription Template',
    seoDescription: 'Modern grid-based prescription layout for multi-specialty consultants.',
  },

  // 11. Eye Specialist Letterhead — Teal banner, specialty logo, Rx pad format
  {
    name: 'Eye Specialist Letterhead',
    slug: 'eye-specialist-letterhead',
    description: 'Specialty clinic letterhead with teal diagonal banner, hospital logo area, doctor name and specialty title, DEA No field, large eye/specialty watermark, patient fields, Rx symbol, date, and footer with appointment booking info. Ideal for ophthalmologists and eye surgeons.',
    category: 'specialty',
    layout: 'classic',
    preview: '/templates/previews/eye-specialist-letterhead.jpg',
    thumbnail: '/templates/thumbnails/eye-specialist-letterhead.jpg',
    styles: {
      primaryColor: '#0891b2',
      accentColor: '#06b6d4',
      bgColor: '#ffffff',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'specialty-banner',
      medicineTableStyle: 'minimal',
      signatureStyle: 'bottom-right',
      footerStyle: 'colored-band',
    },
    sections: [
      { id: 'header', name: 'Teal Specialty Banner with Logo', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Name, S.No, Age, Address', visible: true, order: 2 },
      { id: 'rx-symbol', name: 'Rx Symbol + Date', visible: true, order: 3 },
      { id: 'medicines', name: 'Prescription area with watermark', visible: true, order: 4 },
      { id: 'signature', name: 'Doctor Signature', visible: true, order: 5 },
      { id: 'footer', name: 'Clinic Footer with appointment info', visible: true, order: 6 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 0, right: 0, bottom: 0, left: 0 } },
    isPublished: true, isFeatured: true, isPremium: false,
    tags: ['eye', 'ophthalmology', 'specialist', 'teal', 'letterhead', 'watermark'],
    seoTitle: 'Eye Specialist Prescription Letterhead Template',
    seoDescription: 'Professional eye clinic letterhead with teal banner, specialty watermark, and appointment booking footer.',
  },

  // 12. Simple Rx Pad — Classic minimalist black & white Rx pad
  {
    name: 'Simple Rx Pad',
    slug: 'simple-rx-pad',
    description: 'Ultra-classic minimalist Rx pad format used in pharmacies and general clinics. Large bold Rx symbol top-left, patient name, address lines, a single horizontal divider, generous white space for handwriting medicines, Date and Signature at the bottom. Clean black-and-white professional look.',
    category: 'general',
    layout: 'minimal',
    preview: '/templates/previews/simple-rx-pad.jpg',
    thumbnail: '/templates/thumbnails/simple-rx-pad.jpg',
    styles: {
      primaryColor: '#1a1a1a',
      accentColor: '#555555',
      bgColor: '#f8f8f8',
      fontFamily: 'Georgia, serif',
      headerStyle: 'minimal',
      medicineTableStyle: 'hairline',
      signatureStyle: 'inline',
      footerStyle: 'hairline',
    },
    sections: [
      { id: 'rx-header', name: 'Large Rx symbol with Patient Info', visible: true, order: 1 },
      { id: 'divider', name: 'Bold horizontal divider', visible: true, order: 2 },
      { id: 'writing-area', name: 'Open writing area', visible: true, order: 3 },
      { id: 'footer', name: 'Date and Signature line', visible: true, order: 4 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 30, right: 30, bottom: 30, left: 30 } },
    isPublished: true, isFeatured: false, isPremium: false,
    tags: ['simple', 'rx-pad', 'classic', 'minimal', 'black-white', 'general'],
    seoTitle: 'Simple Rx Pad Prescription Template',
    seoDescription: 'Classic minimalist black-and-white Rx pad format for general practitioners and pharmacies.',
  },

  // 13. Medical Prescription Form — Comprehensive structured form with drug table
  {
    name: 'Medical Prescription Form',
    slug: 'medical-prescription-form',
    description: 'Comprehensive structured medical prescription form with purple Rx branding, date box, full patient info table (name, DOB, age, sex, occupation, insurance, health card, address, diagnosis, vitals, allergies), numbered drug table with unit/dosage columns, and bottom section for diet, history, and doctor signature. Used by specialists who need complete patient documentation.',
    category: 'specialty',
    layout: 'modern',
    preview: '/templates/previews/medical-prescription-form.jpg',
    thumbnail: '/templates/thumbnails/medical-prescription-form.jpg',
    styles: {
      primaryColor: '#4f46e5',
      accentColor: '#818cf8',
      bgColor: '#f5f5f8',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'banner-left',
      medicineTableStyle: 'hospital-grid',
      signatureStyle: 'bottom-right',
      footerStyle: 'minimal',
    },
    sections: [
      { id: 'header', name: 'Rx Symbol + Medical Prescription Title + Date Box', visible: true, order: 1 },
      { id: 'patient-table', name: 'Full Patient Information Table', visible: true, order: 2 },
      { id: 'address-diagnosis', name: 'Address, Diagnosis, Vitals, Allergies', visible: true, order: 3 },
      { id: 'drug-table', name: 'Numbered Drug Table (Drug | Unit | Dosage)', visible: true, order: 4 },
      { id: 'bottom', name: 'Diet, History, Signature', visible: true, order: 5 },
    ],
    printSettings: { pageSize: 'A4', orientation: 'portrait', margins: { top: 10, right: 10, bottom: 10, left: 10 } },
    isPublished: true, isFeatured: true, isPremium: true,
    tags: ['form', 'structured', 'comprehensive', 'drug-table', 'patient-history', 'purple'],
    seoTitle: 'Medical Prescription Form with Drug Table',
    seoDescription: 'Comprehensive structured medical prescription form with patient details, drug table, and diagnosis sections.',
  },
]

export const TEMPLATE_CATEGORIES = [
  { id: 'all', name: 'All Templates', slug: 'all' },
  { id: 'clinic', name: 'Clinic', slug: 'clinic' },
  { id: 'hospital', name: 'Hospital', slug: 'hospital' },
  { id: 'specialty', name: 'Specialty', slug: 'specialty' },
  { id: 'general', name: 'General', slug: 'general' },
  { id: 'pediatric', name: 'Pediatric', slug: 'pediatric' },
] as const
