import type { Template } from '@prescriptionmaker/types'

// =============================================================================
// TEMPLATE CATALOG — 15 Distinct Templates
// Each template has genuinely different layout, typography, hierarchy
// =============================================================================

export const TEMPLATES: Omit<Template, 'id' | 'usageCount' | 'createdAt' | 'updatedAt'>[] = [
  // 1. Classic Medical
  {
    name: 'Classic Medical',
    slug: 'classic-medical',
    description:
      'The timeless prescription format trusted by general practitioners. Full header with doctor details, bordered medicine table, and traditional layout.',
    category: 'general',
    layout: 'classic',
    preview: '/templates/previews/classic-medical.png',
    thumbnail: '/templates/thumbnails/classic-medical.png',
    styles: {
      primaryColor: '#1a3a5c',
      secondaryColor: '#2e6da4',
      accentColor: '#4a9fd4',
      fontFamily: 'Times New Roman, serif',
      headerStyle: 'full',
      medicineTableStyle: 'bordered',
      signatureStyle: 'bottom-right',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'header', name: 'Doctor & Clinic Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Information', visible: true, order: 2 },
      { id: 'vitals', name: 'Vitals', visible: true, order: 3 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 4 },
      { id: 'medicines', name: 'Medicines', visible: true, order: 5 },
      { id: 'tests', name: 'Lab Tests', visible: true, order: 6 },
      { id: 'advice', name: 'Advice & Follow-up', visible: true, order: 7 },
      { id: 'signature', name: 'Signature', visible: true, order: 8 },
      { id: 'footer', name: 'Footer', visible: true, order: 9 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 20, right: 20, bottom: 20, left: 20 },
      showWatermark: false,
    },
    isPublished: true,
    isFeatured: true,
    isPremium: false,
    tags: ['general', 'classic', 'gp', 'traditional'],
    seoTitle: 'Classic Medical Prescription Template',
    seoDescription:
      'Traditional medical prescription template with full doctor header and bordered medicine table. Perfect for general practitioners.',
  },

  // 2. Minimal Clinical
  {
    name: 'Minimal Clinical',
    slug: 'minimal-clinical',
    description:
      'Clean, stripped-down prescription for modern clinics. Minimal borders, generous whitespace, and a focus on readability.',
    category: 'minimal',
    layout: 'minimal',
    preview: '/templates/previews/minimal-clinical.png',
    thumbnail: '/templates/thumbnails/minimal-clinical.png',
    styles: {
      primaryColor: '#0f172a',
      secondaryColor: '#334155',
      accentColor: '#0d9488',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'minimal',
      medicineTableStyle: 'minimal',
      signatureStyle: 'bottom-right',
      footerStyle: 'minimal',
    },
    sections: [
      { id: 'header', name: 'Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient', visible: true, order: 2 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 3 },
      { id: 'medicines', name: 'Medicines', visible: true, order: 4 },
      { id: 'tests', name: 'Tests', visible: true, order: 5 },
      { id: 'advice', name: 'Advice', visible: true, order: 6 },
      { id: 'signature', name: 'Signature', visible: true, order: 7 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 25, right: 25, bottom: 25, left: 25 },
    },
    isPublished: true,
    isFeatured: true,
    isPremium: false,
    tags: ['minimal', 'modern', 'clean'],
    seoTitle: 'Minimal Clinical Prescription Template',
    seoDescription:
      'Clean minimal prescription template for modern clinics with generous whitespace and excellent readability.',
  },

  // 3. Modern Clinic (Teal accent, sans-serif, card-style medicines)
  {
    name: 'Modern Clinic',
    slug: 'modern-clinic',
    description:
      'Contemporary design with teal accent, card-style medicine entries, and a two-section patient area. Ideal for urban clinics.',
    category: 'clinic',
    layout: 'modern',
    preview: '/templates/previews/modern-clinic.png',
    thumbnail: '/templates/thumbnails/modern-clinic.png',
    styles: {
      primaryColor: '#0d9488',
      secondaryColor: '#0f766e',
      accentColor: '#14b8a6',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'logo-left',
      medicineTableStyle: 'card',
      signatureStyle: 'inline',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'header', name: 'Clinic Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Details', visible: true, order: 2 },
      { id: 'vitals', name: 'Vitals', visible: true, order: 3 },
      { id: 'complaint', name: 'Chief Complaint', visible: true, order: 4 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 5 },
      { id: 'medicines', name: 'Prescription', visible: true, order: 6 },
      { id: 'tests', name: 'Investigations', visible: true, order: 7 },
      { id: 'advice', name: 'Advice', visible: true, order: 8 },
      { id: 'followup', name: 'Follow-up', visible: true, order: 9 },
      { id: 'signature', name: 'Doctor Signature', visible: true, order: 10 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 15, right: 20, bottom: 15, left: 20 },
    },
    isPublished: true,
    isFeatured: true,
    isPremium: false,
    tags: ['modern', 'teal', 'urban', 'clinic'],
  },

  // 4. Professional Blue
  {
    name: 'Professional Blue',
    slug: 'professional-blue',
    description:
      'Authoritative deep blue header with striped medicine table. Conveys professionalism and expertise. Popular with consultants and specialists.',
    category: 'specialty',
    layout: 'classic',
    preview: '/templates/previews/professional-blue.png',
    thumbnail: '/templates/thumbnails/professional-blue.png',
    styles: {
      primaryColor: '#1e3a8a',
      secondaryColor: '#1d4ed8',
      accentColor: '#3b82f6',
      fontFamily: 'Georgia, serif',
      headerStyle: 'centered',
      medicineTableStyle: 'striped',
      signatureStyle: 'bottom-right',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'header', name: 'Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient', visible: true, order: 2 },
      { id: 'vitals', name: 'Vitals', visible: true, order: 3 },
      { id: 'diagnosis', name: 'Clinical Diagnosis', visible: true, order: 4 },
      { id: 'medicines', name: 'Medicines', visible: true, order: 5 },
      { id: 'tests', name: 'Investigations', visible: true, order: 6 },
      { id: 'advice', name: 'Instructions', visible: true, order: 7 },
      { id: 'signature', name: 'Signature & Stamp', visible: true, order: 8 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 18, right: 20, bottom: 18, left: 20 },
    },
    isPublished: true,
    isFeatured: false,
    isPremium: false,
    tags: ['professional', 'blue', 'consultant', 'specialist'],
  },

  // 5. Compact Prescription (Half-page A5 style)
  {
    name: 'Compact Prescription',
    slug: 'compact-prescription',
    description:
      'Designed for A5 or half-A4 printing. Compact layout that fits essential information without wasting paper. Great for busy practices.',
    category: 'minimal',
    layout: 'compact',
    preview: '/templates/previews/compact-prescription.png',
    thumbnail: '/templates/thumbnails/compact-prescription.png',
    styles: {
      primaryColor: '#374151',
      secondaryColor: '#6b7280',
      accentColor: '#059669',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'minimal',
      medicineTableStyle: 'minimal',
      signatureStyle: 'bottom-right',
      footerStyle: 'none',
    },
    sections: [
      { id: 'header', name: 'Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient', visible: true, order: 2 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 3 },
      { id: 'medicines', name: 'Rx', visible: true, order: 4 },
      { id: 'advice', name: 'Advice', visible: true, order: 5 },
      { id: 'signature', name: 'Signature', visible: true, order: 6 },
    ],
    printSettings: {
      pageSize: 'A5',
      orientation: 'portrait',
      margins: { top: 12, right: 12, bottom: 12, left: 12 },
    },
    isPublished: true,
    isFeatured: false,
    isPremium: false,
    tags: ['compact', 'a5', 'small', 'quick'],
  },

  // 6. Pediatric Template
  {
    name: 'Pediatric',
    slug: 'pediatric',
    description:
      'Specialized for pediatric practices. Includes weight-based dosing fields, vaccine area, growth parameters, and child-friendly layout.',
    category: 'pediatric',
    layout: 'classic',
    preview: '/templates/previews/pediatric.png',
    thumbnail: '/templates/thumbnails/pediatric.png',
    styles: {
      primaryColor: '#0369a1',
      secondaryColor: '#0284c7',
      accentColor: '#38bdf8',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'full',
      medicineTableStyle: 'striped',
      signatureStyle: 'bottom-right',
      footerStyle: 'minimal',
    },
    sections: [
      { id: 'header', name: 'Pediatrician Header', visible: true, order: 1 },
      { id: 'patient', name: 'Child Details', visible: true, order: 2 },
      { id: 'growth', name: 'Growth Parameters', visible: true, order: 3 },
      { id: 'vitals', name: 'Vitals', visible: true, order: 4 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 5 },
      { id: 'medicines', name: 'Medicines', visible: true, order: 6 },
      { id: 'vaccines', name: 'Vaccines Due', visible: false, order: 7 },
      { id: 'tests', name: 'Investigations', visible: true, order: 8 },
      { id: 'diet', name: 'Diet & Advice', visible: true, order: 9 },
      { id: 'followup', name: 'Next Visit', visible: true, order: 10 },
      { id: 'signature', name: 'Signature', visible: true, order: 11 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 20, right: 20, bottom: 20, left: 20 },
    },
    isPublished: true,
    isFeatured: true,
    isPremium: false,
    tags: ['pediatric', 'children', 'child', 'kids'],
  },

  // 7. Specialist Template
  {
    name: 'Specialist',
    slug: 'specialist',
    description:
      'Tailored for specialist consultants. Includes referral section, detailed clinical findings, and specialist-grade layout hierarchy.',
    category: 'specialty',
    layout: 'two-column',
    preview: '/templates/previews/specialist.png',
    thumbnail: '/templates/thumbnails/specialist.png',
    styles: {
      primaryColor: '#312e81',
      secondaryColor: '#4338ca',
      accentColor: '#818cf8',
      fontFamily: 'Georgia, serif',
      headerStyle: 'logo-left',
      medicineTableStyle: 'bordered',
      signatureStyle: 'bottom-right',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'header', name: 'Specialist Header', visible: true, order: 1 },
      { id: 'referral', name: 'Referred By', visible: true, order: 2 },
      { id: 'patient', name: 'Patient', visible: true, order: 3 },
      { id: 'vitals', name: 'Vitals', visible: true, order: 4 },
      { id: 'history', name: 'History', visible: true, order: 5 },
      { id: 'findings', name: 'Clinical Findings', visible: true, order: 6 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 7 },
      { id: 'medicines', name: 'Treatment', visible: true, order: 8 },
      { id: 'tests', name: 'Investigations', visible: true, order: 9 },
      { id: 'advice', name: 'Advice', visible: true, order: 10 },
      { id: 'followup', name: 'Follow-up', visible: true, order: 11 },
      { id: 'signature', name: 'Signature & Seal', visible: true, order: 12 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 15, right: 15, bottom: 15, left: 15 },
    },
    isPublished: true,
    isFeatured: false,
    isPremium: true,
    tags: ['specialist', 'consultant', 'referral', 'detailed'],
  },

  // 8. Hospital Template
  {
    name: 'Hospital',
    slug: 'hospital',
    description:
      'Institutional hospital prescription with department header, OPD/IPD indicator, MRN number field, and full clinical hierarchy.',
    category: 'hospital',
    layout: 'classic',
    preview: '/templates/previews/hospital.png',
    thumbnail: '/templates/thumbnails/hospital.png',
    styles: {
      primaryColor: '#164e63',
      secondaryColor: '#0e7490',
      accentColor: '#06b6d4',
      fontFamily: 'Arial, sans-serif',
      headerStyle: 'bordered',
      medicineTableStyle: 'bordered',
      signatureStyle: 'bottom-right',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'hospital-header', name: 'Hospital Header', visible: true, order: 1 },
      { id: 'department', name: 'Department & Doctor', visible: true, order: 2 },
      { id: 'opd-ipd', name: 'OPD/IPD Details', visible: true, order: 3 },
      { id: 'patient', name: 'Patient Details', visible: true, order: 4 },
      { id: 'vitals', name: 'Vitals', visible: true, order: 5 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 6 },
      { id: 'medicines', name: 'Prescribed Medicines', visible: true, order: 7 },
      { id: 'tests', name: 'Investigations', visible: true, order: 8 },
      { id: 'advice', name: 'Discharge Advice', visible: true, order: 9 },
      { id: 'signature', name: 'Doctor & HOD Signature', visible: true, order: 10 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 10, right: 15, bottom: 10, left: 15 },
    },
    isPublished: true,
    isFeatured: false,
    isPremium: true,
    tags: ['hospital', 'opd', 'ipd', 'institutional'],
  },

  // 9. Premium White
  {
    name: 'Premium White',
    slug: 'premium-white',
    description:
      'Elegant all-white premium template with hairline borders and refined typography. Exudes luxury and professionalism.',
    category: 'clinic',
    layout: 'minimal',
    preview: '/templates/previews/premium-white.png',
    thumbnail: '/templates/thumbnails/premium-white.png',
    styles: {
      primaryColor: '#111827',
      secondaryColor: '#374151',
      accentColor: '#d4af37',
      fontFamily: 'Playfair Display, serif',
      headerStyle: 'centered',
      medicineTableStyle: 'minimal',
      signatureStyle: 'bottom-right',
      footerStyle: 'minimal',
    },
    sections: [
      { id: 'header', name: 'Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient', visible: true, order: 2 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 3 },
      { id: 'medicines', name: 'Prescription', visible: true, order: 4 },
      { id: 'tests', name: 'Investigations', visible: true, order: 5 },
      { id: 'advice', name: 'Advice', visible: true, order: 6 },
      { id: 'signature', name: 'Signature', visible: true, order: 7 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 30, right: 25, bottom: 30, left: 25 },
    },
    isPublished: true,
    isFeatured: true,
    isPremium: true,
    tags: ['premium', 'luxury', 'elegant', 'white'],
  },

  // 10. Elegant Clinical
  {
    name: 'Elegant Clinical',
    slug: 'elegant-clinical',
    description:
      'Sophisticated slate-toned template with subtle ornamental dividers. Perfect for senior clinicians who want a refined yet clinical look.',
    category: 'general',
    layout: 'classic',
    preview: '/templates/previews/elegant-clinical.png',
    thumbnail: '/templates/thumbnails/elegant-clinical.png',
    styles: {
      primaryColor: '#1e293b',
      secondaryColor: '#334155',
      accentColor: '#0d9488',
      fontFamily: 'Lora, serif',
      headerStyle: 'full',
      medicineTableStyle: 'striped',
      signatureStyle: 'bottom-right',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'header', name: 'Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Information', visible: true, order: 2 },
      { id: 'vitals', name: 'Examination', visible: true, order: 3 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 4 },
      { id: 'medicines', name: 'Rx', visible: true, order: 5 },
      { id: 'tests', name: 'Investigations', visible: true, order: 6 },
      { id: 'advice', name: 'Instructions', visible: true, order: 7 },
      { id: 'followup', name: 'Follow-up', visible: true, order: 8 },
      { id: 'signature', name: 'Signature', visible: true, order: 9 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 22, right: 22, bottom: 22, left: 22 },
    },
    isPublished: true,
    isFeatured: false,
    isPremium: false,
    tags: ['elegant', 'clinical', 'refined', 'professional'],
  },

  // 11. Two-Column Medical
  {
    name: 'Two-Column Medical',
    slug: 'two-column-medical',
    description:
      'Efficient two-column layout puts patient info and vitals side by side, maximizing content density for experienced practitioners.',
    category: 'general',
    layout: 'two-column',
    preview: '/templates/previews/two-column-medical.png',
    thumbnail: '/templates/thumbnails/two-column-medical.png',
    styles: {
      primaryColor: '#065f46',
      secondaryColor: '#047857',
      accentColor: '#10b981',
      fontFamily: 'Inter, sans-serif',
      headerStyle: 'logo-left',
      medicineTableStyle: 'bordered',
      signatureStyle: 'inline',
      footerStyle: 'minimal',
    },
    sections: [
      { id: 'header', name: 'Header', visible: true, order: 1 },
      { id: 'patient-vitals', name: 'Patient + Vitals (2-col)', visible: true, order: 2 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 3 },
      { id: 'medicines', name: 'Medicines', visible: true, order: 4 },
      { id: 'tests', name: 'Tests & Advice (2-col)', visible: true, order: 5 },
      { id: 'signature', name: 'Signature', visible: true, order: 6 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 15, right: 18, bottom: 15, left: 18 },
    },
    isPublished: true,
    isFeatured: false,
    isPremium: false,
    tags: ['two-column', 'efficient', 'dense', 'modern'],
  },

  // 12. Simple Print
  {
    name: 'Simple Print',
    slug: 'simple-print',
    description:
      'No-frills, printer-optimized layout. Maximum ink savings, fast printing, suitable for high-volume practices with basic prescriptions.',
    category: 'minimal',
    layout: 'minimal',
    preview: '/templates/previews/simple-print.png',
    thumbnail: '/templates/thumbnails/simple-print.png',
    styles: {
      primaryColor: '#000000',
      secondaryColor: '#333333',
      accentColor: '#555555',
      fontFamily: 'Arial, sans-serif',
      headerStyle: 'minimal',
      medicineTableStyle: 'minimal',
      signatureStyle: 'bottom-right',
      footerStyle: 'none',
    },
    sections: [
      { id: 'header', name: 'Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient', visible: true, order: 2 },
      { id: 'medicines', name: 'Rx', visible: true, order: 3 },
      { id: 'signature', name: 'Signature', visible: true, order: 4 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 10, right: 10, bottom: 10, left: 10 },
    },
    isPublished: true,
    isFeatured: false,
    isPremium: false,
    tags: ['simple', 'print', 'minimal', 'ink-saving'],
  },

  // 13. Modern Minimal
  {
    name: 'Modern Minimal',
    slug: 'modern-minimal',
    description:
      'Contemporary minimalist template with bold typography and strategic whitespace. Inspired by modern product design principles.',
    category: 'minimal',
    layout: 'modern',
    preview: '/templates/previews/modern-minimal.png',
    thumbnail: '/templates/thumbnails/modern-minimal.png',
    styles: {
      primaryColor: '#0f172a',
      secondaryColor: '#475569',
      accentColor: '#f59e0b',
      fontFamily: 'DM Sans, sans-serif',
      headerStyle: 'logo-left',
      medicineTableStyle: 'card',
      signatureStyle: 'bottom-left',
      footerStyle: 'none',
    },
    sections: [
      { id: 'header', name: 'Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient', visible: true, order: 2 },
      { id: 'diagnosis', name: 'Diagnosis & Notes', visible: true, order: 3 },
      { id: 'medicines', name: 'Medications', visible: true, order: 4 },
      { id: 'tests', name: 'Tests', visible: false, order: 5 },
      { id: 'advice', name: 'Advice', visible: true, order: 6 },
      { id: 'signature', name: 'Signature', visible: true, order: 7 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 28, right: 28, bottom: 28, left: 28 },
    },
    isPublished: true,
    isFeatured: true,
    isPremium: false,
    tags: ['modern', 'minimal', 'design', 'bold'],
  },

  // 14. Traditional Prescription
  {
    name: 'Traditional Prescription',
    slug: 'traditional-prescription',
    description:
      'Faithful to the traditional handwritten prescription format. Preprinted-paper style with ruled lines and classic Rx symbol.',
    category: 'general',
    layout: 'traditional',
    preview: '/templates/previews/traditional.png',
    thumbnail: '/templates/thumbnails/traditional.png',
    styles: {
      primaryColor: '#78350f',
      secondaryColor: '#92400e',
      accentColor: '#d97706',
      fontFamily: 'Courier New, monospace',
      headerStyle: 'full',
      medicineTableStyle: 'minimal',
      signatureStyle: 'bottom-right',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'header', name: 'Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Info', visible: true, order: 2 },
      { id: 'rx-body', name: 'Rx Body', visible: true, order: 3 },
      { id: 'advice', name: 'Advice', visible: true, order: 4 },
      { id: 'signature', name: 'Signature', visible: true, order: 5 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 15, right: 15, bottom: 15, left: 15 },
    },
    isPublished: true,
    isFeatured: false,
    isPremium: false,
    tags: ['traditional', 'rx', 'classic', 'handwritten-style'],
  },

  // 15. Dental / Dermatology Specialty
  {
    name: 'Specialty Clinic',
    slug: 'specialty-clinic',
    description:
      'Configurable specialty template suitable for dental, dermatology, ophthalmology, ENT and other specialist branches. Flexible section ordering.',
    category: 'specialty',
    layout: 'specialty',
    preview: '/templates/previews/specialty-clinic.png',
    thumbnail: '/templates/thumbnails/specialty-clinic.png',
    styles: {
      primaryColor: '#4c1d95',
      secondaryColor: '#6d28d9',
      accentColor: '#a78bfa',
      fontFamily: 'Nunito, sans-serif',
      headerStyle: 'logo-left',
      medicineTableStyle: 'card',
      signatureStyle: 'bottom-right',
      footerStyle: 'bordered',
    },
    sections: [
      { id: 'header', name: 'Specialty Header', visible: true, order: 1 },
      { id: 'patient', name: 'Patient Details', visible: true, order: 2 },
      { id: 'vitals', name: 'Relevant Parameters', visible: true, order: 3 },
      { id: 'history', name: 'Chief Complaint / History', visible: true, order: 4 },
      { id: 'findings', name: 'Examination Findings', visible: true, order: 5 },
      { id: 'diagnosis', name: 'Diagnosis', visible: true, order: 6 },
      { id: 'treatment', name: 'Treatment Plan', visible: true, order: 7 },
      { id: 'medicines', name: 'Medicines', visible: true, order: 8 },
      { id: 'tests', name: 'Investigations', visible: true, order: 9 },
      { id: 'advice', name: 'Homecare Advice', visible: true, order: 10 },
      { id: 'followup', name: 'Next Appointment', visible: true, order: 11 },
      { id: 'signature', name: 'Signature', visible: true, order: 12 },
    ],
    printSettings: {
      pageSize: 'A4',
      orientation: 'portrait',
      margins: { top: 18, right: 20, bottom: 18, left: 20 },
    },
    isPublished: true,
    isFeatured: true,
    isPremium: true,
    tags: ['specialty', 'dental', 'dermatology', 'ent', 'ophthalmology'],
  },
]

export const TEMPLATE_CATEGORIES = [
  { id: 'all', name: 'All Templates', slug: 'all' },
  { id: 'general', name: 'General Practice', slug: 'general' },
  { id: 'minimal', name: 'Minimal', slug: 'minimal' },
  { id: 'clinic', name: 'Clinic', slug: 'clinic' },
  { id: 'hospital', name: 'Hospital', slug: 'hospital' },
  { id: 'pediatric', name: 'Pediatric', slug: 'pediatric' },
  { id: 'specialty', name: 'Specialty', slug: 'specialty' },
  { id: 'custom', name: 'Custom', slug: 'custom' },
] as const
